depi-project/Depi-Project/Controllers/DepartmentController.cs
using Depi_Project.context;
using Depi_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace Depi_Project.Controllers
{
    public class DepartmentController : Controller
    {
        ApplicationContext context = new ApplicationContext();
        public IActionResult Index()
        {
            List<Department> depModel = context.Departments.ToList();
            return View(depModel);
        }
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }
        [HttpPost]
        public IActionResult New(Department New_department)
        {
            if (New_department.Department_Name != null)
            {
                context.Departments.Add(New_department);
                context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(New_department);
        }

        

        [HttpGet]
        public IActionResult Delete(int id) 
        {
            var departmentModdel = context.Departments.Find(id);
            if (departmentModdel == null)
            {
                return NotFound();
            }

            return View(departmentModdel);

        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var depModel = context.Departments.FirstOrDefault(D => D.Department_Id == id);
            if (depModel == null)
            {
                return NotFound();
            } 
            context.Departments.Remove(depModel); 
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

depi-project/Depi-Project/Controllers/EmployeeController.cs
using Depi_Project.context;
using Depi_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Depi_Project.Controllers
{
    public class EmployeeController : Controller
    {
        ApplicationContext context = new ApplicationContext() ;
        public IActionResult Index()
        {
            List<Employee> employeesModel = context.Employees.Include(e =>e.department).ToList();


            return View(employeesModel);
        }
        [HttpGet]
        public IActionResult New() 
        {
            ViewData["Depts"] = context.Departments.ToList();
            return View(); 
        }
        [HttpPost]
        public IActionResult New(Employee Newemployee) 
        {
            if (Newemployee.Name == null && Newemployee.department==null&&Newemployee.Age==0)
            {
                ViewData["Depts"] = context.Departments.ToList();
                return View(Newemployee);
            }
            context.Employees.Add(Newemployee);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id) 
        {
            Employee empModil = context.Employees.Include(e => e.department).FirstOrDefault(e => e.Employee_Id == id);

            if (empModil == null) 
            {
                return NotFound();  
            }
         
            return View(empModil);
        }
       



        [HttpGet]
        public IActionResult Delete(int id)
        {
            var EmployeeModdel = context.Employees.Find(id);
            if (EmployeeModdel == null)
            {
                return NotFound();
            }

            return View(EmployeeModdel);

        }

        [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var empModel = context.Employees.FirstOrDefault(D => D.Employee_Id == id);
            if (empModel == null)
            {
                return NotFound();
            }
            context.Employees.Remove(empModel);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id) 
        {
            Employee empModle =context.Employees.FirstOrDefault(d => d.Employee_Id == id);
            ViewData["Depts"] = context.Departments.ToList();
            return View(empModle);

        }
        [HttpPost]
        public IActionResult Edit( [FromRoute] int id, Employee newEmp) 
        {
            if (newEmp.Name == null && newEmp.department == null && newEmp.Age == 0)
            {
                return View(newEmp);
            }
            Employee oldEmp = context.Employees.FirstOrDefault(e => e.Employee_Id == id);
            
            oldEmp.Name = newEmp.Name;
            oldEmp.Address = newEmp.Address;
            oldEmp.Age = newEmp.Age;
            oldEmp.PhoneNumber = newEmp.PhoneNumber;
            oldEmp.department = newEmp.department;
            


            context.SaveChanges();
            return RedirectToAction("Index");
        
        }
    }

}

depi-project/Depi-Project/Controllers/EquipmentController.cs
using Depi_Project.context;
using Depi_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Depi_Project.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Depi_Project.IdentityModels;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace Depi_Project.Controllers
{
    public class EquipmentController : Controller
    {
        private readonly ApplicationContext _context;
        public EquipmentController(ApplicationContext context)
        {
            _context = context;
        }
        
        public IActionResult Index(int page = 1, int pageSize = 9)
        {
            var equipmentList = _context.Equipments.ToList(); 
            var totalItems = equipmentList.Count(); 
            var totalPages = (int)Math.Ceiling(totalItems / (double)pageSize); 

            
            var equipmentToShow = equipmentList.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.CurrentPage = page; 
            ViewBag.TotalPages = totalPages; 

            return View(equipmentToShow); 
        }


        public async Task<IActionResult> Create()
        {
            var createViewModel = new EquipmentFormViewModel
            {
                StatusOptions = new List<string> { "Available", "In Maintenance", "Out of Service" }
            };
            return View("EquipmentForm", createViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EquipmentFormViewModel model)
        {
            if (!ModelState.IsValid)
            {


                return View("EquipmentForm", model);
            }
            var Equip = new Equipment()
            {
                Equipment_Name = model.Equipment_Name,
                Maintainance_Date = model.Maintainance_Date,
                Status = model.Status,
            };
            _context.Equipments.Add(Equip);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));

        }
        

        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)  
                return BadRequest();

            var equipment = await _context.Equipments.FindAsync(id);

            if (equipment == null)
                return NotFound();

            _context.Equipments.Remove(equipment);
            await _context.SaveChangesAsync();

     
            return RedirectToAction(nameof(Index));
        }


        public IActionResult Edit(int id)
        {
            var equipment = _context.Equipments.Find(id);
            if (equipment == null)
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new EquipmentFormViewModel
            {
                Equipment_Id = equipment.Equipment_Id,
                Equipment_Name = equipment.Equipment_Name,
                Maintainance_Date = equipment.Maintainance_Date,
                Status = equipment.Status,
                StatusOptions = new List<string> { "Available", "In Maintenance", "Out of Service" }
            };

            return View("EquipmentForm", model);
        }


        [HttpPost]
        public IActionResult Edit(int id, EquipmentFormViewModel model)
        {
            var equipment = _context.Equipments.Find(id);
            if (equipment == null)
            {
                return RedirectToAction(nameof(Index));
            }

            if (!ModelState.IsValid)
            {
                return View("EquipmentForm", model);
            }

            equipment.Equipment_Name = model.Equipment_Name;
            equipment.Status = model.Status;
            equipment.Maintainance_Date = model.Maintainance_Date;

            _context.Equipments.Update(equipment);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }


    }
}

depi-project/Depi-Project/Views/Shared/_newLayout.cshtml
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/all.min.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

       <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Depi_Project.styles.css" asp-append-version="true" />


    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />

     <!-- SweetAlert2 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.10/dist/sweetalert2.min.css" rel="stylesheet">

    <!-- SweetAlert2 JS -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.6.10/dist/sweetalert2.all.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
    <link
      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;500&display=swap"
      rel="stylesheet"
    />
    <title>@ViewData["Title"] - Gym Management System </title>
  </head>
  <body>
    <div class="loader">
      <h1>Loading<span>....</span></h1>
    </div>
    <div class="page-content index-page">
      <div class="sidebar">
        <div class="brand">
            
          <i class="fa-solid fa-xmark xmark"></i>
          <h3 class="brand-name">Gym Management System </h3>
          
        </div>
        
        <ul>

          @if(!User.Identity.IsAuthenticated){
            <li>
            <a asp-controller="Account" asp-action="Register" class="sidebar-link">
              <i class="fa-solid fa-user"></i>
              <span>Register</span>
            </a>
          </li>
          <li>
            <a asp-controller="Account" asp-action="Login" class="sidebar-link">
              <i class="fa-solid fa-right-to-bracket"></i>
              <span>Login</span>
            </a>
          </li>
          }else{

            <li>
            <a asp-controller="Home" asp-action="Index" class="sidebar-link">
              <i class="fa-solid fa-user-tie"></i>
              <span> Welcome @User.Identity.Name</span>
            </a>
          </li>
          <li>
            <a asp-controller="Home" asp-action="Index" class="sidebar-link">
              <i class="fa-solid fa-house"></i>
              <span>Dashboard</span>
            </a>
          </li>

          <li>
            <a asp-controller="Employee" asp-action="Index" class="sidebar-link">
            <i class="fa-solid fa-user-group"></i>
              <span>Employees</span>
            </a>
          </li>

           <li>
            <a asp-controller="Department" asp-action="Index" class="sidebar-link">
              <i class="fa-solid fa-user-group"></i>
              <span>Departments</span>
            </a>
          </li>

          <li>
              <a asp-controller="Equipment" asp-action="Index" class="sidebar-link">
              <i class="fa-solid fa-dumbbell"></i>
              <span> Equipments </span>
            </a>
          </li>
          
          <li>
            <a asp-controller="Trainee" asp-action="Index" class="sidebar-link">
            <i class="fa-solid fa-user-group"></i>
              <span> Trainees</span>
            </a>
          </li>
          <li>
            <a asp-controller="Subscription" asp-action="index" class="sidebar-link">
              <i class="fa-solid fa-money-bill"></i>
              <span> Subscriptions</span>
            </a>
          </li>
          <li>
            <a asp-controller="Account" asp-action="LogOut" class="sidebar-link">
              <i class="fa-solid fa-right-from-bracket"></i>
              <span>Log Out</span>
            </a>
          </li>
          }
          <!-- ... other menu items with asp-controller and asp-action ... -->

        </ul>
      </div>
      <main>
        <div class="header">
          <i class="fa-solid fa-bars bar-item"></i>
          <div class="search">
            <form asp-action="#" asp-controller="#">
            <input type="number" name="id" value=""  />
            <input type="submit" class="btn btn-danger" style="padding: 10 px; margin: 5 px;">
            </form>
          </div>

          <div class="profile">
            <span class="bell"><i class="fa-regular fa-bell fa-lg"></i></span>

            <img src="~/images/avatar.png" alt="No Image" />
          </div>
        </div>
        <div class="main-content">
          <div class="title">
            <h1>@ViewData["Title"]</h1>
          </div>
          <div class="container">
            <main role="main" class="pb-3">
              @RenderBody()
            </main>
          </div>
        </div>
      </main>
    </div>
    
    <script src="~/js/script.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
  </body>
</html>